# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Krewe Du Moon
email: jacqnelson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you love Anime, or Sailor Moon (or talking cats with crescent shapes on their heads) check us out! We are fully costumed, throw-prepped and ready to roll with the IKOC.
  Many Members will also be seen at various Comic Cons indulging in all our Geeky/ Nerdy/ "Comic Book Cutie" awesomeness!.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: krewedumoon
github_username:  spaceotterinspace
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
